# Generated by Django 4.2.11 on 2024-09-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather3h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WmoStationNumber', models.IntegerField()),
                ('StationNameThai', models.CharField(max_length=255)),
                ('StationNameEnglish', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('DateTime', models.DateField()),
                ('StationPressure', models.FloatField()),
                ('MeanSeaLevelPressure', models.FloatField()),
                ('AirTemperature', models.FloatField()),
                ('DewPoint', models.FloatField()),
                ('RelativeHumidity', models.FloatField()),
                ('VaporPressure', models.FloatField()),
                ('LandVisibility', models.FloatField()),
                ('WindDirection', models.IntegerField()),
                ('WindSpeed', models.FloatField()),
                ('Rainfall', models.FloatField()),
                ('Rainfall24Hr', models.FloatField()),
            ],
            options={
                'db_table': 'weather3h',
                'ordering': ['DateTime'],
            },
        ),
    ]
