# Generated by Django 4.2.11 on 2024-09-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather3h',
            name='AirTemperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='DateTime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='DewPoint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='LandVisibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='MeanSeaLevelPressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='Province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='Rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='Rainfall24Hr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='RelativeHumidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='StationNameEnglish',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='StationNameThai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='StationPressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='VaporPressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='WindDirection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='WindSpeed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather3h',
            name='WmoStationNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
