# Generated by Django 4.2.11 on 2024-09-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_log_alter_weather3h_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['last_build_time']},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='DateTime',
            new_name='last_build_time',
        ),
    ]
